# Practical_6: Numpy

In [1]:
import numpy as np

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

In [6]:
integers=np.arange(1,11)
print(integers)

[ 1  2  3  4  5  6  7  8  9 10]


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

In [9]:
zeros=np.zeros([3,3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

In [15]:
exo3=np.linspace(0,5,10)
exo3

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
#check to see if it's ok
for i in range(len(exo3)-1) :
    print(exo3[i+1]-exo3[i])

0.5555555555555556
0.5555555555555556
0.5555555555555556
0.5555555555555556
0.5555555555555554
0.5555555555555558
0.5555555555555558
0.5555555555555554
0.5555555555555554


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

In [37]:
exo4=np.eye(5)
exo4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

In [25]:
exo5=np.random.random([4,4])
exo5

array([[0.90566686, 0.76042644, 0.06265497, 0.72396305],
       [0.33133947, 0.5035343 , 0.04724431, 0.60118879],
       [0.26306146, 0.82066446, 0.24404195, 0.3023824 ],
       [0.22211944, 0.1825483 , 0.04357409, 0.17191778]])

---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

In [27]:
#create the array
exo6=np.array([[4,5,6],[6,8,9]], int)
#check the shape
print(exo6.shape)

(2, 3)


---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

In [31]:
#previous array
p=np.arange(16)
p.shape=(4,4)
print(p)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

In [38]:
#create the array
exo8=np.random.random([6,8])
print(exo8.dtype)

float64


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

In [39]:
ar=np.arange(1,100)
print(ar[ar%2==0])

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [45]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [154]:
exo6=np.random.randint(10,50, size=(6,6))
exo6

array([[39, 26, 30, 28, 24, 25],
       [27, 35, 27, 42, 27, 26],
       [36, 22, 40, 27, 27, 26],
       [10, 41, 47, 19, 10, 48],
       [32, 42, 12, 13, 41, 45],
       [37, 28, 23, 39, 21, 32]])

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

In [67]:
exo11=np.random.randint(15, size=(4,5))
print(exo11)
print(' submatrix is : \n', exo11[:3,2:5])

[[ 4 13  2  8  9]
 [ 3  7 10  8  7]
 [ 4  5  2 10  3]
 [ 3 14  8 11  8]]
 submatrix is : 
 [[ 2  8  9]
 [10  8  7]
 [ 2 10  3]]


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

In [78]:

array=np.random.randint(1,100, 156)
s=sum(array)
s

7853

In [91]:
#help(np.sum)

In [196]:

#sum total
sum_total=np.sum(array)
print('The total sum is : ', sum_total)

The total sum is :  898


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

In [104]:
#two dimensions
array=np.random.randint(150, size=(5,6))
print('the array is : \n', array)
#mean, median and sd of the colums
mean_column=np.mean(array, axis=0)
median_column=np.median(array, axis=0)
sd_column=np.std(array, axis=0)
print('For each column, the mean is {}, the median {} and the standard deviation is {} : '.format(mean_column, median_column,sd_column))
#mean, median and sd of the row
mean_row=np.mean(array, axis=1)
median_row=np.median(array, axis=1)
sd_row=np.std(array, axis=1)
#print(' '.format(mean_row, median_row, sd_row)
print('\n For each row, the mean is {}, the median {} and the standard deviation is {} : '.format(mean_row, median_row, sd_row))

the array is : 
 [[ 22   2  41  45   9 135]
 [109  42 107  75  55 109]
 [ 47  51  92  27  90  77]
 [ 26 138 141   1  29 103]
 [ 88  31  37 147  70 138]]
For each column, the mean is [ 58.4  52.8  83.6  59.   50.6 112.4], the median [ 47.  42.  92.  45.  55. 109.] and the standard deviation is [34.47085726 45.68325733 39.74720116 50.1677187  28.79305472 22.44638055] : 

 For each row, the mean is [42.33333333 82.83333333 64.         73.         85.16666667], the median [31.5 91.  64.  66.  79. ] and the standard deviation is [44.24803825 27.25445937 24.         56.38853311 44.9199906 ] : 


---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

In [106]:
#two dimensions
array=np.random.randint(150, size=(5,6))
print('the array is : \n', array)
#min, max and sd of the colums
min_column=np.min(array, axis=0)
max_column=np.max(array, axis=0)
print('For each column, the min is {}, the max is {}  : '.format(min_column, max_column))
#min, max and sd of the row
min_row=np.min(array, axis=1)
max_row=np.max(array, axis=1)
#print(' '.format(min_row, max_row, sd_row)
print('\n For each row, the min is {}, the max {} : '.format(min_row, max_row))
min_total=np.min(array)
max_total=np.max(array)
print('The min of the total array is {} and the maximum is {} '.format(min_total, max_total))

the array is : 
 [[ 90  21 133  62 101  84]
 [ 97 111  21  72  24 126]
 [ 34  34 141 127  97  72]
 [104 105 142 128  15 119]
 [ 66 140  92  75   5   6]]
For each column, the min is [34 21 21 62  5  6], the max is [104 140 142 128 101 126]  : 

 For each row, the min is [21 21 34 15  5], the max [133 126 141 142 140] : 
The min of the total array is 5 and the maximum is 142 


---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

In [121]:
np.random.seed(10)
array=np.random.randint(100,size=20)
print(array)
index=np.argmax(array)
print('The index of the maximum value is : ', index)

[ 9 15 64 28 89 93 29  8 73  0 40 36 16 11 54 88 62 33 72 78]
The index of the maximum value is :  5


---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [124]:
np.random.seed(10)
array=np.random.randint(100,size=20)
print(array)
reverse_array=np.flip(array)
print(reverse_array)

[ 9 15 64 28 89 93 29  8 73  0 40 36 16 11 54 88 62 33 72 78]
[78 72 33 62 88 54 11 16 36 40  0 73  8 29 93 89 28 64 15  9]


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

In [132]:
np.random.seed(10)
matrix1=np.random.randint(14, size=(3,3))
matrix2=np.random.randint(14, size=(3,3))
print('matrix1 : \n', matrix1)
print('matrix2 : \n ', matrix2)
print('matrix1 x matrix2 = : \n ',matrix1*matrix2)

matrix1 : 
 [[ 9 13  4]
 [ 0  1 11]
 [12  9 13]]
matrix2 : 
  [[ 0 13  1]
 [10  8  9]
 [ 0 10  8]]
matrix1 x matrix2 = : 
  [[  0 169   4]
 [  0   8  99]
 [  0  90 104]]


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

In [136]:
Given_matrix=np.random.randint(12, size=5)
diag_matrix=np.diag(Given_matrix)
print('GIven matrix : ', Given_matrix)
print('Diag Matrix : \n', diag_matrix)


GIven matrix :  [6 5 3 9 6]
Diag Matrix : 
 [[6 0 0 0 0]
 [0 5 0 0 0]
 [0 0 3 0 0]
 [0 0 0 9 0]
 [0 0 0 0 6]]


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

In [140]:
np.random.seed(10)
matrix1=np.random.randint(14, size=(3,3))
matrix2=np.random.randint(14, size=(3,3))
print('m1 : \n', matrix1)
print('m2 : \n', matrix2)
print('m1 * m2 = : \n ', np.dot(matrix1, matrix2))

m1 : 
 [[ 9 13  4]
 [ 0  1 11]
 [12  9 13]]
m2 : 
 [[ 0 13  1]
 [10  8  9]
 [ 0 10  8]]
m1 * m2 = : 
  [[130 261 158]
 [ 10 118  97]
 [ 90 358 197]]


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

In [150]:
np.random.seed(10)
m=np.random.randint(14, size=(3,3))
print('m 2D : \n ', m)
n=np.concatenate(m)
print('n 1D : \n ', n)

m 2D : 
  [[ 9 13  4]
 [ 0  1 11]
 [12  9 13]]
n 1D : 
  [ 9 13  4  0  1 11 12  9 13]


---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

In [164]:
ar1=np.random.randint(10, size=15)
ar2=np.random.randint(10, size=15)
Ver=np.vstack((ar1, ar2))
print('Fisrt : ', ar1)
print('Second : ', ar2)
print('Final: ', Ver)

Fisrt :  [2 9 5 1 0 2 3 1 4 2 0 2 8 8 8]
Second :  [6 5 8 8 8 0 6 1 2 8 3 9 8 6 7]
Final:  [[2 9 5 1 0 2 3 1 4 2 0 2 8 8 8]
 [6 5 8 8 8 0 6 1 2 8 3 9 8 6 7]]


---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

In [163]:
ar1=np.random.randint(10, size=15)
ar2=np.random.randint(10, size=15)
Ver=np.hstack((ar1, ar2))
print('Fisrt : ', ar1)
print('Second : ', ar2)
print('Final: ', Ver)

Fisrt :  [7 1 7 1 2 9 2 7 4 6 7 3 2 3 9]
Second :  [2 5 0 7 2 6 5 7 3 7 0 3 6 0 7]
Final:  [7 1 7 1 2 9 2 7 4 6 7 3 2 3 9 2 5 0 7 2 6 5 7 3 7 0 3 6 0 7]


---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

In [173]:
#help(np.split)

In [172]:
ar1=np.random.randint(10, size=(3,6))
b=np.split(ar1, 3)
print('First matrix : \n', ar1)
print('Sub matrices : \n', b)

First matrix : 
 [[3 1 9 0 0 2]
 [4 2 9 9 7 1]
 [3 5 4 1 7 8]]
Sub matrices : 
 [array([[3, 1, 9, 0, 0, 2]]), array([[4, 2, 9, 9, 7, 1]]), array([[3, 5, 4, 1, 7, 8]])]


---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

In [182]:
ar1=np.random.random([4,5])
ar2 =np.round(ar1, 2)
print('Fisrt : \n', ar1)
print('ROunded : \n ', ar2)

Fisrt : 
 [[0.2363534  0.08981164 0.19447817 0.61580788 0.93208368]
 [0.69108395 0.56284705 0.2637558  0.52714688 0.80438291]
 [0.29507589 0.18333855 0.01973246 0.74332123 0.0382934 ]
 [0.43367967 0.83208476 0.01345856 0.50933539 0.4795487 ]]
ROunded : 
  [[0.24 0.09 0.19 0.62 0.93]
 [0.69 0.56 0.26 0.53 0.8 ]
 [0.3  0.18 0.02 0.74 0.04]
 [0.43 0.83 0.01 0.51 0.48]]


---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

In [184]:
ar1=np.random.randint(10, size=15)
bb=ar1[np.unique(ar1)]
print('Array : \n ', ar1)
print('Unique elements : \n ', bb)

Array : 
  [3 1 7 0 7 0 9 4 0 9 7 3 7 0 1]
Unique elements : 
  [3 1 0 7 4 9]


---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

In [187]:
ar1=np.random.randint(100, size=15)
print(' First matrix : \n', ar1)
ar1[ar1< 12]=12
print(' Final matrix : \n', ar1)

 First matrix : 
 [81 48  9 28 34 76 73 35 85 71  9 29 12  5 72]
 Final matrix : 
 [81 48 12 28 34 76 73 35 85 71 12 29 12 12 72]


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

In [190]:
ar1=np.random.randint(10, size=15)
print(' First matrix : \n', ar1)
b=np.cumsum(ar1)
print('Cumulative sum : \n ', b)

 First matrix : 
 [2 3 0 3 5 3 5 7 8 9 5 9 6 7 6]
Cumulative sum : 
  [ 2  5  5  8 13 16 21 28 36 45 50 59 65 72 78]


---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

In [194]:
ar1=np.random.randint(2, size=15)
print(' First matrix : \n', ar1)
b=sum(ar1!=0)
print('Number of non zeros elements : ', b)

 First matrix : 
 [1 1 1 0 0 0 0 0 0 1 1 1 0 0 0]
Number of non zeros elements :  6


---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

In [195]:
ar1=np.random.randint(100, size=15)
print(' First matrix : \n', ar1)
b=np.sort(ar1)
print('Sorted matrix : \n', b)

 First matrix : 
 [99 54 19  2 19 95 69 73 99 95  1 93 14 93 14]
Sorted matrix : 
 [ 1  2 14 14 19 19 54 69 73 93 93 95 95 99 99]


---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

In [198]:
array=np.random.randint(100, size=(3,3))
print('the array is : \n', array)
#sum of the colums
sum_column=np.sum(array, axis=0)
print('The sum of each column is : ', sum_column)
#sum of the rows
sum_row=np.sum(array, axis=1)
print('The sum of each row is : ', sum_row)

the array is : 
 [[37 12 36]
 [42 41 57]
 [25 28 95]]
The sum of each column is :  [104  81 188]
The sum of each row is :  [ 85 140 148]


---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

In [204]:
array=np.random.randint(100, size=(3,3))
print('Previous array \n ', array)
mean_column=np.mean(array, axis=0)
sd_column=np.std(array, axis=0)
norm = (array-mean_column)/(sd_column)
print('Normalize matrix : \n ', norm)

Previous array 
  [[88 33  8]
 [75 90 49]
 [68 35 53]]
Normalize matrix : 
  [[ 1.32745468 -0.74463142 -1.40964666]
 [-0.2413554   1.41353761  0.60647589]
 [-1.08609928 -0.66890619  0.80317077]]


---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

In [207]:
ar1=np.random.randint(10, size=(5,5))
ar2=np.random.randint(10, size=(5,5))
print('Matrix 1 : \n ', ar1)
print('Matrix 2 : \n ', ar2)
print('M1 * M2 : \n ', np.dot(ar1, ar2))

Matrix 1 : 
  [[8 2 5 8 7]
 [4 9 5 0 6]
 [3 8 4 1 0]
 [9 9 4 2 2]
 [6 4 6 7 0]]
Matrix 2 : 
  [[2 5 1 3 8]
 [2 5 4 4 5]
 [2 3 4 1 5]
 [8 0 0 4 5]
 [1 2 8 0 5]]
M1 * M2 : 
  [[101  79  92  69 174]
 [ 42  92 108  53 132]
 [ 38  67  51  49  89]
 [ 62 106  77  75 157]
 [ 88  68  46  68 133]]


---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

In [210]:
ar1=np.random.randint(10, size=(3,3))
print('Matrix : \n', ar1)
print('The trace is : ', np.trace(ar1))

Matrix : 
 [[1 4 0]
 [5 4 9]
 [6 1 2]]
The trace is :  7


---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

In [218]:
ar1=np.random.randint(10, size=(4,5))
print('Matrix : \n', ar1)
ar1[[0,2]]=ar1[[2,0]]
print('New Matrix : \n', ar1)

Matrix : 
 [[6 4 7 4 9]
 [1 0 4 5 7]
 [0 6 0 9 5]
 [8 2 8 3 2]]
New Matrix : 
 [[0 6 0 9 5]
 [1 0 4 5 7]
 [6 4 7 4 9]
 [8 2 8 3 2]]


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

In [227]:
ar1=np.random.randint(10, size=15)
print('Array : \n', ar1)
b=ar1[...,None]
b

Array : 
 [4 8 0 9 1 7 1 2 7 6 6 7 5 1 9]


array([[4],
       [8],
       [0],
       [9],
       [1],
       [7],
       [1],
       [2],
       [7],
       [6],
       [6],
       [7],
       [5],
       [1],
       [9]])

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

In [232]:
ar1=np.random.randint(10, size=(3,3))
print('Matrix : \n', ar1)
print('Determinant is : \n', float(np.linalg.det(ar1)))

Matrix : 
 [[9 0 6]
 [4 9 1]
 [0 0 6]]
Determinant is : 
 486.0000000000004


---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

In [247]:
np.random.seed(10)
ar1=np.random.randint(10, size=(2,2))
bb=np.linalg.eig(ar1)
print('Eigen values : \n', bb[0])
print('EIgen vector : \n', bb[1])

Eigen values : 
 [9. 1.]
EIgen vector : 
 [[ 1.         -0.4472136 ]
 [ 0.          0.89442719]]


---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

In [258]:
np.random.seed(10)
# A system equations has the form AX=B and the solution is $X=A^{-1}B$
A=np.random.randint(50, size=(3,3))
B=np.random.randint(50, size=(3,1))
A_inverse=np.linalg.inv(A)
X=np.dot(A_inverse,B)
print('The matrix A is : \n', A)
print('The matrix B is : \n', B)
print('The solution is : \n', X)

The matrix A is : 
 [[ 9 36 15]
 [ 0 49 28]
 [25 29 48]]
The matrix B is : 
 [[29]
 [49]
 [ 8]]
The solution is : 
 [[-0.79830795]
 [ 1.01895093]
 [-0.03316413]]


---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

In [261]:
gaussian_noise = np.random.normal(5, 1, 100)
gaussian_noise

array([5.45187984, 4.14052582, 4.46520547, 6.03287114, 4.86376425,
       5.17637307, 5.31085074, 6.72937588, 4.75933806, 3.97264798,
       5.42401507, 6.40862087, 5.43999202, 4.57176561, 4.68798732,
       4.43111661, 3.41505899, 6.05535316, 3.07342089, 5.69858388,
       4.25379857, 4.84337334, 4.80636406, 6.13912535, 5.36221796,
       4.40908701, 5.38936304, 4.47300385, 4.48569209, 5.89760917,
       5.98925209, 5.25922513, 4.97580681, 5.35849666, 4.62245364,
       5.69563116, 6.02484465, 6.70775544, 3.03288278, 4.12904333,
       3.89317452, 5.27512366, 4.63554386, 3.83484653, 3.65693012,
       6.45339286, 5.00116945, 4.98807962, 5.71588314, 3.81423145,
       4.3636721 , 4.38918616, 3.6806086 , 4.43827158, 5.20538457,
       4.04663932, 5.32151795, 3.47906133, 2.83854708, 5.34531329,
       5.87896938, 5.56276301, 5.28843534, 3.9935185 , 5.05397842,
       3.17327674, 4.90808516, 4.74681684, 6.38059377, 4.31657117,
       4.68314885, 3.9827296 , 4.02587623, 4.966761  , 5.98288

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

In [264]:
ar1=np.random.randint(20, size=(4,4))
print('Matrix : \n', ar1)
diag_elements=np.diag(ar1)
print('Diagonal elements :', diag_elements)

Matrix : 
 [[ 9 12 16  4]
 [ 6  9  8 16]
 [11  7 17  7]
 [17  1 11 14]]
Diagonal elements : [ 9  9 17 14]


---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

In [266]:
array=np.random.randint(200, size=100)


---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---